// lib/locations.ts
// Country + language options. locationCode maps to DataForSEO where known;
// countries without a code still work for crawl + AI-visibility (which use the
// country name). Full DataForSEO list: https://docs.dataforseo.com/v3/serp/google/locations/

export interface LocationOption {
  country: string;
  countryCode: string;
  locationCode?: number; // DataForSEO location_code (optional; not all countries mapped)
}

export const COUNTRIES: LocationOption[] = [
  { country: "Kenya", countryCode: "KE", locationCode: 2404 },
  { country: "United States", countryCode: "US", locationCode: 2840 },
  { country: "United Kingdom", countryCode: "GB", locationCode: 2826 },
  { country: "Nigeria", countryCode: "NG", locationCode: 2566 },
  { country: "South Africa", countryCode: "ZA", locationCode: 2710 },
  { country: "Ghana", countryCode: "GH", locationCode: 2288 },
  { country: "Tanzania", countryCode: "TZ", locationCode: 2834 },
  { country: "Uganda", countryCode: "UG", locationCode: 2800 },
  { country: "Afghanistan", countryCode: "AF" },
  { country: "Albania", countryCode: "AL" },
  { country: "Algeria", countryCode: "DZ" },
  { country: "Andorra", countryCode: "AD" },
  { country: "Angola", countryCode: "AO" },
  { country: "Antigua and Barbuda", countryCode: "AG" },
  { country: "Argentina", countryCode: "AR" },
  { country: "Armenia", countryCode: "AM" },
  { country: "Australia", countryCode: "AU", locationCode: 2036 },
  { country: "Austria", countryCode: "AT" },
  { country: "Azerbaijan", countryCode: "AZ" },
  { country: "Bahamas", countryCode: "BS" },
  { country: "Bahrain", countryCode: "BH" },
  { country: "Bangladesh", countryCode: "BD" },
  { country: "Barbados", countryCode: "BB" },
  { country: "Belarus", countryCode: "BY" },
  { country: "Belgium", countryCode: "BE" },
  { country: "Belize", countryCode: "BZ" },
  { country: "Benin", countryCode: "BJ" },
  { country: "Bhutan", countryCode: "BT" },
  { country: "Bolivia", countryCode: "BO" },
  { country: "Bosnia and Herzegovina", countryCode: "BA" },
  { country: "Botswana", countryCode: "BW" },
  { country: "Brazil", countryCode: "BR" },
  { country: "Brunei", countryCode: "BN" },
  { country: "Bulgaria", countryCode: "BG" },
  { country: "Burkina Faso", countryCode: "BF" },
  { country: "Burundi", countryCode: "BI" },
  { country: "Cambodia", countryCode: "KH" },
  { country: "Cameroon", countryCode: "CM" },
  { country: "Canada", countryCode: "CA", locationCode: 2124 },
  { country: "Cape Verde", countryCode: "CV" },
  { country: "Central African Republic", countryCode: "CF" },
  { country: "Chad", countryCode: "TD" },
  { country: "Chile", countryCode: "CL" },
  { country: "China", countryCode: "CN" },
  { country: "Colombia", countryCode: "CO" },
  { country: "Comoros", countryCode: "KM" },
  { country: "Congo (Brazzaville)", countryCode: "CG" },
  { country: "Congo (Kinshasa)", countryCode: "CD" },
  { country: "Costa Rica", countryCode: "CR" },
  { country: "Croatia", countryCode: "HR" },
  { country: "Cuba", countryCode: "CU" },
  { country: "Cyprus", countryCode: "CY" },
  { country: "Czechia", countryCode: "CZ" },
  { country: "Denmark", countryCode: "DK" },
  { country: "Djibouti", countryCode: "DJ" },
  { country: "Dominica", countryCode: "DM" },
  { country: "Dominican Republic", countryCode: "DO" },
  { country: "Ecuador", countryCode: "EC" },
  { country: "Egypt", countryCode: "EG" },
  { country: "El Salvador", countryCode: "SV" },
  { country: "Equatorial Guinea", countryCode: "GQ" },
  { country: "Eritrea", countryCode: "ER" },
  { country: "Estonia", countryCode: "EE" },
  { country: "Eswatini", countryCode: "SZ" },
  { country: "Ethiopia", countryCode: "ET" },
  { country: "Fiji", countryCode: "FJ" },
  { country: "Finland", countryCode: "FI" },
  { country: "France", countryCode: "FR", locationCode: 2250 },
  { country: "Gabon", countryCode: "GA" },
  { country: "Gambia", countryCode: "GM" },
  { country: "Georgia", countryCode: "GE" },
  { country: "Germany", countryCode: "DE", locationCode: 2276 },
  { country: "Greece", countryCode: "GR" },
  { country: "Grenada", countryCode: "GD" },
  { country: "Guatemala", countryCode: "GT" },
  { country: "Guinea", countryCode: "GN" },
  { country: "Guinea-Bissau", countryCode: "GW" },
  { country: "Guyana", countryCode: "GY" },
  { country: "Haiti", countryCode: "HT" },
  { country: "Honduras", countryCode: "HN" },
  { country: "Hungary", countryCode: "HU" },
  { country: "Iceland", countryCode: "IS" },
  { country: "India", countryCode: "IN", locationCode: 2356 },
  { country: "Indonesia", countryCode: "ID" },
  { country: "Iran", countryCode: "IR" },
  { country: "Iraq", countryCode: "IQ" },
  { country: "Ireland", countryCode: "IE" },
  { country: "Israel", countryCode: "IL" },
  { country: "Italy", countryCode: "IT" },
  { country: "Ivory Coast", countryCode: "CI" },
  { country: "Jamaica", countryCode: "JM" },
  { country: "Japan", countryCode: "JP" },
  { country: "Jordan", countryCode: "JO" },
  { country: "Kazakhstan", countryCode: "KZ" },
  { country: "Kiribati", countryCode: "KI" },
  { country: "Kuwait", countryCode: "KW" },
  { country: "Kyrgyzstan", countryCode: "KG" },
  { country: "Laos", countryCode: "LA" },
  { country: "Latvia", countryCode: "LV" },
  { country: "Lebanon", countryCode: "LB" },
  { country: "Lesotho", countryCode: "LS" },
  { country: "Liberia", countryCode: "LR" },
  { country: "Libya", countryCode: "LY" },
  { country: "Liechtenstein", countryCode: "LI" },
  { country: "Lithuania", countryCode: "LT" },
  { country: "Luxembourg", countryCode: "LU" },
  { country: "Madagascar", countryCode: "MG" },
  { country: "Malawi", countryCode: "MW" },
  { country: "Malaysia", countryCode: "MY" },
  { country: "Maldives", countryCode: "MV" },
  { country: "Mali", countryCode: "ML" },
  { country: "Malta", countryCode: "MT" },
  { country: "Marshall Islands", countryCode: "MH" },
  { country: "Mauritania", countryCode: "MR" },
  { country: "Mauritius", countryCode: "MU" },
  { country: "Mexico", countryCode: "MX" },
  { country: "Micronesia", countryCode: "FM" },
  { country: "Moldova", countryCode: "MD" },
  { country: "Monaco", countryCode: "MC" },
  { country: "Mongolia", countryCode: "MN" },
  { country: "Montenegro", countryCode: "ME" },
  { country: "Morocco", countryCode: "MA" },
  { country: "Mozambique", countryCode: "MZ" },
  { country: "Myanmar", countryCode: "MM" },
  { country: "Namibia", countryCode: "NA" },
  { country: "Nauru", countryCode: "NR" },
  { country: "Nepal", countryCode: "NP" },
  { country: "Netherlands", countryCode: "NL" },
  { country: "New Zealand", countryCode: "NZ" },
  { country: "Nicaragua", countryCode: "NI" },
  { country: "Niger", countryCode: "NE" },
  { country: "North Korea", countryCode: "KP" },
  { country: "North Macedonia", countryCode: "MK" },
  { country: "Norway", countryCode: "NO" },
  { country: "Oman", countryCode: "OM" },
  { country: "Pakistan", countryCode: "PK" },
  { country: "Palau", countryCode: "PW" },
  { country: "Palestine", countryCode: "PS" },
  { country: "Panama", countryCode: "PA" },
  { country: "Papua New Guinea", countryCode: "PG" },
  { country: "Paraguay", countryCode: "PY" },
  { country: "Peru", countryCode: "PE" },
  { country: "Philippines", countryCode: "PH" },
  { country: "Poland", countryCode: "PL" },
  { country: "Portugal", countryCode: "PT" },
  { country: "Qatar", countryCode: "QA" },
  { country: "Romania", countryCode: "RO" },
  { country: "Russia", countryCode: "RU" },
  { country: "Rwanda", countryCode: "RW" },
  { country: "Saint Kitts and Nevis", countryCode: "KN" },
  { country: "Saint Lucia", countryCode: "LC" },
  { country: "Saint Vincent and the Grenadines", countryCode: "VC" },
  { country: "Samoa", countryCode: "WS" },
  { country: "San Marino", countryCode: "SM" },
  { country: "Sao Tome and Principe", countryCode: "ST" },
  { country: "Saudi Arabia", countryCode: "SA" },
  { country: "Senegal", countryCode: "SN" },
  { country: "Serbia", countryCode: "RS" },
  { country: "Seychelles", countryCode: "SC" },
  { country: "Sierra Leone", countryCode: "SL" },
  { country: "Singapore", countryCode: "SG" },
  { country: "Slovakia", countryCode: "SK" },
  { country: "Slovenia", countryCode: "SI" },
  { country: "Solomon Islands", countryCode: "SB" },
  { country: "Somalia", countryCode: "SO" },
  { country: "South Korea", countryCode: "KR" },
  { country: "South Sudan", countryCode: "SS" },
  { country: "Spain", countryCode: "ES" },
  { country: "Sri Lanka", countryCode: "LK" },
  { country: "Sudan", countryCode: "SD" },
  { country: "Suriname", countryCode: "SR" },
  { country: "Sweden", countryCode: "SE" },
  { country: "Switzerland", countryCode: "CH" },
  { country: "Syria", countryCode: "SY" },
  { country: "Taiwan", countryCode: "TW" },
  { country: "Tajikistan", countryCode: "TJ" },
  { country: "Thailand", countryCode: "TH" },
  { country: "Timor-Leste", countryCode: "TL" },
  { country: "Togo", countryCode: "TG" },
  { country: "Tonga", countryCode: "TO" },
  { country: "Trinidad and Tobago", countryCode: "TT" },
  { country: "Tunisia", countryCode: "TN" },
  { country: "Turkey", countryCode: "TR" },
  { country: "Turkmenistan", countryCode: "TM" },
  { country: "Tuvalu", countryCode: "TV" },
  { country: "Ukraine", countryCode: "UA" },
  { country: "United Arab Emirates", countryCode: "AE", locationCode: 2784 },
  { country: "Uruguay", countryCode: "UY" },
  { country: "Uzbekistan", countryCode: "UZ" },
  { country: "Vanuatu", countryCode: "VU" },
  { country: "Vatican City", countryCode: "VA" },
  { country: "Venezuela", countryCode: "VE" },
  { country: "Vietnam", countryCode: "VN" },
  { country: "Yemen", countryCode: "YE" },
  { country: "Zambia", countryCode: "ZM" },
  { country: "Zimbabwe", countryCode: "ZW" },
];

export interface LanguageOption {
  language: string;
  languageCode: string; // DataForSEO language_code
}

export const LANGUAGES: LanguageOption[] = [
  { language: "English", languageCode: "en" },
  { language: "Swahili", languageCode: "sw" },
  { language: "French", languageCode: "fr" },
  { language: "German", languageCode: "de" },
  { language: "Arabic", languageCode: "ar" },
  { language: "Spanish", languageCode: "es" },
  { language: "Portuguese", languageCode: "pt" },
];

export function resolveLocation(country: string): LocationOption {
  return COUNTRIES.find((c) => c.country === country) ?? COUNTRIES[0];
}
export function resolveLanguage(language: string): LanguageOption {
  return LANGUAGES.find((l) => l.language === language) ?? LANGUAGES[0];
}
